- name: Install PostgreSQL
  hosts: database
  become: true
  tasks:
    - name: Install PostgreSQL
      apt:
        name: "postgresql-{{ postgresql_version }}"
        state: present
      vars:
        postgresql_version: "{{ hostvars[inventory_hostname]['postgresql_version'] }}"
        postgresql_data_dir: "{{ hostvars[inventory_hostname]['postgresql_data_dir'] }}"
    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: true
