---
- name: Установка и настройка веб-сервера
  hosts: test

  vars:
    new_username: user1
    ssh_public_key: "{{ lookup('file', './ansibel/web/user1.pub') }}"
    php_fpm_listen_port: 9000

  tasks:
    - name: Добавление нового пользователя с авторизацией по ключу
      user:
        name: "{{ new_username }}"
        state: present
        createhome: yes

    - name: Добавление публичного ключа нового пользователя
      authorized_key:
        user: "{{ new_username }}"
        key: "{{ ssh_public_key }}"
        state: present

    - name: Установка nginx
      apt:
        name: nginx
        state: present

    - name: Установка php-fpm
      apt:
        name: php-fpm
        state: present

    - name: Настройка php-fpm для прослушивания порта 9000
      lineinfile:
        path: /etc/php/8.1/fpm/pool.d/www.conf
        regexp: '^listen = '
        line: 'listen = 127.0.0.1:{{ php_fpm_listen_port }}'

    - name: Поднятие php-fpm
      service:
        name: php8.1-fpm
        state: started

    - name: Настройка nginx для проксирования запросов на php-fpm
      template:
        src: nginx_php_config.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx

    - name: Настройка nginx для прослушивания порта 9000
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^listen '
        line: 'listen 9000;'
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
