---
# roles/php/tasks/main.yml
- name: Установка php-fpm
  apt:
    name: php-fpm
    state: present

- name: Настройка php-fpm для прослушивания порта 9000
  lineinfile:
    path: /etc/php/8.1/fpm/pool.d/www.conf
    regexp: '^listen = '
    line: 'listen = 127.0.0.1:9000'

- name: Перезапуск php-fpm
  service:
    name: php8.1-fpm
    state: restarted
