- name: Установка или удаление почтового сервера Postfix
  hosts: test
  become: yes

  tasks:
    - name: Установка Postfix
      package:
        name: postfix
        state: present
      tags:
        - init
        - postfix

    - name: Удаление Postfix
      package:
        name: postfix
        state: absent
      tags:
        - drop
        - postfix
