---
- name: Создание пользователя и установка SSH-ключа
  hosts: test
  become: yes

  vars:
    encrypted_key: |
     fgsdsd
     
  tasks:
    - name: Создание пользователя user1
      user:
        name: user1
        shell: /bin/bash
        createhome: yes

    - name: Создание директории .ssh
      file:
        path: /home/user1/.ssh
        state: directory
        owner: user1
        group: user1
        mode: '0700'

    - name: Установка SSH-ключа для пользователя user1
      copy:
        content: "{{ encrypted_key }}"
        dest: /home/user1/.ssh/id_rsa
        owner: user1
        group: user1
        mode: '0600'
