<<<<<<< HEAD
- name: Создание пользователя и настройка SSH-ключа
=======
----
  - name: Создание пользователя и настройка SSH-ключа
>>>>>>> 83633bb45c03ab798922a14e63413cca1d887081
  hosts: your_host
  become: yes

  tasks:
    - name: Создание пользователя user1
      user:
        name: user1
        shell: /bin/bash
        createhome: yes

    - name: Создание директории .ssh для пользователя user1
      file:
        path: /home/user1/.ssh
        state: directory
        owner: user1
        group: user1
        mode: '0700'

    - name: Установка SSH-ключа для пользователя user1
      copy:
        content: "{{ lookup('file', './ansible/user1_key') }}"
        dest: /home/user1/.ssh/id_rsa
        owner: user1
        group: user1
        mode: '0600'
